version: "3"

services:
  # mysql:
  #   image: mariadb:10.5
  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret
  #   volumes:
  #     - mysql_volume:/var/lib/mysql

  # pdns_mysql:
  #   image: rajeev/pdns:v12
  #   environment:
  #     AUTOCONF: mysql
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: root
  #     MYSQL_PASS: secret
  #   command:
  #     - --cache-ttl=120
  #     - --allow-axfr-ips=127.0.0.1,123.1.2.3

  psql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      # POSTGRES_DB: pdns
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./postgres-schema.sql:/docker-entrypoint-initdb.d/1_initial.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2_data.sql

  pdns_psql:
    image: rajeev/pdns:v12
    environment:
      AUTOCONF: postgres
      PGSQL_HOST: psql
      PGSQL_USER: postgres
      PGSQL_PASS: secret
    ports:
      - "53:53"
      - "53:53/udp"
      - "8088:8081"
    command:
      - --cache-ttl=120
      - --allow-axfr-ips=127.0.0.1,123.1.2.3

  # pdns_sqlite:
  #   image: rajeev/pdns:v12
  #   environment:
  #     AUTOCONF: sqlite
  #     SQLITE_DB: /data/db.sqlite
  #   command:
  #     - --cache-ttl=120
  #     - --allow-axfr-ips=127.0.0.1,123.1.2.3
  #   volumes:
  #     - sqlite_volume:/data

volumes:
  mysql_volume: {}
  psql_volume: {}
  sqlite_volume: {}
